version: '3'
services:
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - product-db

  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - customer-db

  discovery-service:
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - cart-db

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    depends_on:
      - order-db

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    depends_on:
      - auth-db

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - account-db

  pricing-service:
    build:
      context: ./pricing-service
      dockerfile: Dockerfile
    ports:
      - "8086:8086"

  customer-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: to
      POSTGRES_DB: turkcell-srs
    ports:
      - "5433:5432"

  order-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: to
      POSTGRES_DB: order-db
    ports:
      - "5434:5432"

  cart-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: to
      POSTGRES_DB: cart-db
    ports:
      - "5435:5432"

  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: to
      POSTGRES_DB: auth-db
    ports:
      - "5436:5432"

  account-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: to
      POSTGRES_DB: account-service
    ports:
      - "5437:5432"

  product-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: to
      POSTGRES_DB: productmaster-db
    ports:
      - "5438:5432"
