server:
  port: 8082
  error:
    include-message: always

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customers/**, /api/v1/address/** , /api/v1/contact/** , /testing/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**, api/v1/categories/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/v1/accounts/**
        - id: price-service
          uri: lb://price-service
          predicates:
            - Path=/api/v1/price/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/cart/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
      discovery:
        locator:
          enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
